name: Train and Build Model Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training pipeline
        run: |
          python train-pipeline.py

      - name: Verify artifacts produced
        run: |
          ls -R artifacts

      - name: Upload model artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: artifacts/

      - name: Build Docker image
        run: |
          docker build -t my-ml-model:latest .
